### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by temp3l** [edubart/luamon#1]
Not a bug!

I Needed these on a fresh ubuntu install:

luarocks install luamon INOTIFY_INCDIR=/usr/include/x86_64-linux-gnu

luarocks install luafilesystem 

luarocks install penlight

**Comment by Andre-LA** [comment]
Tried here on Pop!_OS 20.10 (based on Ubuntu 20.10), indeed it required me to run these commands:

`luarocks install luamon INOTIFY_INCDIR=/usr/include/x86_64-linux-gnu`
`luarocks install penlight`

**Comment by edubart** [comment]
I've added penlight to the dependencies in luarocks server, and a note about `INOTIFY_INCDIR` on the README.
