### ISSUE TITLE
Wait for child process to finish before restarting

### ISSUE THREAD

**Issue by atticus-sullivan** [edubart/luamon#4]
Hi,

I'm using this to build latex files continuously while writing the source. Unfortunately some things break in my setup when aborting the build (some files containing caches kinda break).

It would be nice to have a flag "always wait for build to complete", which results in just completing the build and if normally a new build would run in the meantime, the already running build isn't aborted but only a flag is being set which issues an new build directly afterwards. I'd explicitly not be queuing this (just make a flag), to prevent that a huge amount of pending builds build up.

I'm not entirely sure how to add this to the existing project (thus this is only an issue and no PR), but maybe [`waitpid`](https://luaposix.github.io/luaposix/modules/posix.sys.wait.html) or [`kill(0)`](https://luaposix.github.io/luaposix/modules/posix.signal.html#kill) (to check if the child is still running) (see [this post](https://stackoverflow.com/a/9153003)) can be used to achieve this.

**Comment by edubart** [comment]
Waiting for a build to complete is something you can do outside. Luamon sends `SIGINT` to kill a process, you can handle `SIGINT` gracefully to wait a build to complete and all tasks to finish in your application or using a "proxy" script. But there is a catch, Luamon expects the application to finish handling `SIGINT` in just 20ms, if this timeouts Luamon will send and `SIGILL` to forcely kill the application, maybe that is causing issues for you, you can change the kill delay with some large value like `-k 1000`  or some other larger value to wait more time before sending a kill.

**Comment by atticus-sullivan** [comment]
Hm, in a make based workflow it will probably be hard to handle this signal with make (if not wanting to place everything in a `oneshell`).
But, for now I'm fine with that.
